#!/bin/bash

# Setup git global defaults

echo "☕️ Setting up git global defaults"

git config --global user.email "andrewusher@gmail.com"
echo "✅ git user.email -> andrewusher00@gmail.com"

git config --global user.name "Andrew Usher"
echo "✅ git user.name -> Andrew Usher"
