#!/bin/bash

echo "☕️ Installing fd"
sudo apt install fd-find
echo "✅ fd installed"

echo "☕️ Installing fzf"
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
echo "✅ fzf installed"